FROM php:8.2-apache

# Install the MySQL extension so your PHP script can communicate with MySQL
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# Copy your local PHP files into the container's web server folder
COPY . /var/www/html/

# Expose port 80 for web traffic
EXPOSE 80